<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hasuikeNabeshima [
<!ELEMENT hasuikeNabeshima (hansyu+, haichaku*)>
<!ELEMENT hansyu (name*, yomi*, role*, birth*, death*, father*, fatherInLaw*, grfather*, mother*, grMother*, altName*, profiles*, firstWife*, nextWife*, secondWife*)>
<!ELEMENT haichaku (name*, yomi*, role*, birth*, death*, father*, fatherInLaw*, grfather*, mother*, grMother*, altName*, profiles*, firstWife*, nextWife*, secondWife*)>
<!ELEMENT father (role*, name*, yomi*, altName*)>
<!ELEMENT fatherInLaw (role*, name*, yomi*, altName*)>
<!ELEMENT grFather (role*, name*, yomi*, altName*)>
<!ELEMENT mother (role*, name*, yomi*, altName*, father*)>
<!ELEMENT grMother (role*, name*, yomi*, altName*)>
<!ELEMENT altName (main*, first*, other*)>
<!ELEMENT profiles (event+)>
<!ELEMENT event (start*, end*, title)>
<!ELEMENT firstWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT nextWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT secondWife (name*, birth*, death*, fatherInLaw*, father*, brother*, children*)>
<!ELEMENT children (son*, daughter*)>
<!ELEMENT son (order, name*, yomi*, altName*, role*, birth*, death*, father*, mother*, fatherInLaw*, wife*, fiance*, description*, adopted*)>
<!ELEMENT daughter (order, name*, yomi*, altName*, birth*, death*, father*, mother*, fatherInLaw*, husband*, fiance*, description*,adopted*)>
<!ELEMENT husband (role*, name*, yomi*, altName*, birth*, death*, father*, mother*)>
<!ELEMENT wife (role*, name*, yomi*, birth*, death*, father*, mother*)>
<!ELEMENT brother (role*, name*, birth*, death*, father*, mother*)>
<!ELEMENT fiance (role*, name*, birth*, death*, father*, mother*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT yomi (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT birth (#PCDATA)>
<!ELEMENT death (#PCDATA)>
<!ELEMENT main (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT other (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT adopted (#PCDATA)>
]>

<hasuikeNabeshima>
<hansyu>
	<name>鍋島直澄</name>
	<yomi>naozumi</yomi>
	<role>肥前蓮池藩初代藩主</role>
	<birth>1616</birth>
	<death>1669</death>
	<father>
		<role>肥前佐賀藩初代藩主</role>
		<name>鍋島勝茂</name>
		<yomi>katsushige</yomi>
	</father>
	<mother>
		<name>高源院</name>
		<altName>
			<other>菊姫</other>
		</altName>
		<father>
			<name>岡部長盛</name>
		</father>
	</mother>
	<altName>
		<main>甲斐守</main>
		<first>千熊丸</first>
	</altName>
	<profiles>
			<event>
				<start>1635</start>
				<title>従五位下</title>
			</event>
			<event>
				<start>1635</start>
				<title>甲斐守</title>
			</event>
			<event>
				<start>1639</start>
				<end>1665</end>
				<title>蓮池鍋島藩初代藩主</title>
			</event>
	</profiles>
	<firstWife>
		<name></name>
		<father>
			<role>播磨姫路藩主</role>
			<name>tadaakira</name>
			<yomi>松平忠明</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直之</name>
				<yomi>naoyuki</yomi>
				<role>肥前蓮池藩二代藩主</role>
				<birth>1643</birth>
				<death>1725</death>
			</son>
		</children>
	</firstWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直守</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>大塚氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島之治</name>
				<fatherInLaw>
					<name>鍋島直守</name>
				</fatherInLaw>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩二代藩主</role>
					<name>鍋島光茂</name>
					<yomi>mitsushige</yomi>
				</fatherInLaw>
				<husband>
					<role>肥前鹿島藩二代藩主</role>
					<name>鍋島直條</name>
					<yomi>naoeda</yomi>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>松平好房</name>
					<yomi>yoshifusa</yomi>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島之映</name>
				<fatherInLaw>
					<name>鍋島貞恒</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>伊香加氏</name>
		<children>
			<son>
				<order>2</order>
				<name>鍋島直称</name>
				<yomi>naonori</yomi>
				<role>肥前蓮池藩三代藩主</role>
				<birth>1667</birth>
				<death>1736</death>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島之徳</name>
			</son>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島直之</name>
	<yomi>naoyuki</yomi>
	<role>肥前蓮池藩二代藩主</role>
	<birth>1643</birth>
	<death>1725</death>
	<father>
		<role>肥前蓮池藩初代藩主</role>
		<name>鍋島直澄</name>
		<yomi>naozumi</yomi>
	</father>
	<altName>
		<main>摂津</main>
		<first>千熊丸</first>
	</altName>
	<profiles>
			<event>
				<start>1660</start>
				<title>従五位下</title>
			</event>
			<event>
				<start>1665</start>
				<end>1708</end>
				<title>肥前蓮池藩二代藩主</title>
			</event>
	</profiles>
	<firstWife>
		<name></name>
		<father>
			<role>三代諫早領主</role>
			<name>諫早茂敬</name>
			<yomi>shigeyoshi</yomi>
		</father>
	</firstWife>
	<nextWife>
		<fatherInLaw>
			<role>肥前佐賀藩二代藩主</role>
			<name>鍋島光茂</name>
			<yomi>mitsushige</yomi>
		</fatherInLaw>
		<father>
			<name>榊原照清</name>
		</father>
		<children>
			<son>
				<order>3</order>
				<name>鍋島直称</name>
				<yomi>naonori</yomi>
				<role>肥前蓮池藩三代藩主</role>
				<birth>1667</birth>
				<death>1736</death>
				<adopted>養子</adopted>
			</son>
			<son>
				<order>4</order>
				<name>鍋島直富</name>
				<birth>1673</birth>
				<death>1694</death>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
		</children>
	</nextWife>
	<secondWife>
		<name>原氏</name>
		<children>
			<son>
				<order>1</order>
				<name>千熊</name>
			</son>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島直称</name>
	<yomi>naonori</yomi>
	<role>肥前蓮池藩三代藩主</role>
	<birth>1667</birth>
	<death>1736</death>
	<father>
		<role>肥前蓮池藩初代藩主</role>
		<name>鍋島直澄</name>
		<yomi>naozumi</yomi>
	</father>
	<fatherInLaw>
		<role>肥前蓮池藩二代藩主</role>
		<name>鍋島直之</name>
		<yomi>naoyuki</yomi>
	</fatherInLaw>
	<altName>
		<main>主税</main>
		<first>熊之助</first>
		<other>之紀</other>
	</altName>
	<profiles>
			<event>
				<start>1700</start>
				<title>従五位下</title>
			</event>
			<event>
				<start>1700</start>
				<title>朝散大夫</title>
			</event>
			<event>
				<start>1700</start>
				<title>甲斐守</title>
			</event>
			<event>
				<start>1708</start>
				<end>1717</end>
				<title>肥前蓮池藩三代藩主</title>
			</event>
	</profiles>
	<firstWife>
		<name>興祥院</name>
		<fatherInLaw>
			<role>肥前佐賀藩三代藩主</role>
			<name>鍋島綱茂</name>
			<yomi>tsunashige</yomi>
		</fatherInLaw>
		<father>
			<name>小花和成武</name>
		</father>
		<children>
			<son>
				<order>2</order>
				<name>鍋島直恒</name>
				<yomi>naotsune</yomi>
				<role>肥前蓮池藩四代藩主</role>
				<birth>1702</birth>
				<death>1749</death>
			</son>
			<son>
				<order>4</order>
				<name>鍋島称起</name>
				<fatherInLaw>
					<name>鍋島之晨</name>
				</fatherInLaw>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩四代藩主</role>
					<name>鍋島吉茂</name>
					<yomi>yoshishige</yomi>
				</fatherInLaw>
				<husband>
					<role>権大納言</role>
					<name>日野資時</name>
					<yomi>suketoki</yomi>
				</husband>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<husband>
					<name>諫早茂候</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島之基</name>
				<fatherInLaw>
					<name>鍋島亀之徳</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>熊之助</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>中野好古</name>
				<fatherInLaw>
					<name>中野好志</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>峯豊方</name>
				<fatherInLaw>
					<name>峯五郎右衛門某</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>	
			<son>
				<order>1</order>
				<name>成富盛隆</name>
				<fatherInLaw>
					<name>成富盛政</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>	
			<son>
				<order>1</order>
				<name>牟田玄義</name>
				<fatherInLaw>
					<name>牟田玄充</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>島内氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<name>松枝貞昌</name>
				</fatherInLaw>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<fatherInLaw>
					<name>中澤政員</name>
				</fatherInLaw>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島直恒</name>
	<yomi>naotsune</yomi>
	<role>肥前蓮池藩四代藩主</role>
	<birth>1702</birth>
	<death>1749</death>
	<father>
		<role>肥前蓮池藩三代藩主</role>
		<name>鍋島直称</name>
		<yomi>naonori</yomi>
	</father>
	<altName>
		<main>左京</main>
		<first>弁五郎</first>
		<other>称就</other>
		<other>主税</other>
	</altName>
	<profiles>
		<event>
			<start>1715</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1715</start>
			<title>摂津守</title>
		</event>
		<event>
			<start>1717</start>
			<end>1749</end>
			<title>肥前蓮池藩四代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<name></name>
		<fatherInLaw>
			<role>肥前佐賀藩四代藩主</role>
			<name>yoshishige</name>
			<yomi>鍋島吉茂</yomi>
		</fatherInLaw>
		<father>
			<role>肥前佐賀藩二代藩主</role>
			<name>鍋島光茂</name>
			<yomi>mitsushige</yomi>
		</father>
	</firstWife>
	<secondWife>
		<name>犬塚氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直興</name>
				<yomi>naooki</yomi>
				<role>肥前蓮池藩五代藩主</role>
				<birth>1730</birth>
				<death>1757</death>
			</son>
			<son>
				<order>2</order>
				<name>鍋島喬良</name>
				<fatherInLaw>
					<name>鍋島種良</name>
				</fatherInLaw>
			</son>
			<son>
				<order>3</order>
				<name>牟田守尋</name>
				<fatherInLaw>
					<name>牟田守陣</name>
				</fatherInLaw>
			</son>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩七代藩主</role>
					<name>鍋島重茂</name>
					<yomi>shigemoti</yomi>
				</fatherInLaw>
				<husband>
					<role>参議</role>
					<name>堀河康実</name>
					<yomi>yasuzane</yomi>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>長崎氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<name>中野好古</name>
				</fatherInLaw>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>大隈氏</name>
		<children>
			<son>
				<order>2</order>
				<name>鍋島直寛</name>
				<yomi>naohiro</yomi>
				<role>肥前蓮池藩六代藩主</role>
				<birth>1746</birth>
				<death>1773</death>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<name>犬塚常芳</name>
				</fatherInLaw>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<fatherInLaw>
					<name>鍋島称信</name>
				</fatherInLaw>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島直興</name>
	<yomi>naooki</yomi>
	<role>肥前蓮池藩五代藩主</role>
	<birth>1730</birth>
	<death>1757</death>
	<father>
		<role>肥前蓮池藩四代藩主</role>
		<name>鍋島直恒</name>
		<yomi>naotsune</yomi>
	</father>
	<altName>
		<main>直賢</main>
		<first>直之助</first>
	</altName>
	<profiles>
			<event>
				<start>1750</start>
				<end>1757</end>
				<title>肥前蓮池藩五代藩主</title>
			</event>
	</profiles>
	<profiles>
			<event>
				<start>1750</start>
				<title>従五位下</title>
			</event>
			<event>
				<start>1750</start>
				<title>甲斐守</title>
			</event>
	</profiles>
	<firstWife>
		<name></name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直寛</name>
				<yomi>naohiro</yomi>
				<role>肥前蓮池藩六代藩主</role>
				<birth>1746</birth>
				<death>1773</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島直寛</name>
	<yomi>naohiro</yomi>
	<role>肥前蓮池藩六代藩主</role>
	<birth>1746</birth>
	<death>1773</death>
	<father>
		<role>肥前蓮池藩四代藩主</role>
		<name>鍋島直恒</name>
		<yomi>naotsune</yomi>
	</father>
	<fatherInLaw>
		<role>肥前蓮池藩五代藩主</role>
		<name>鍋島直興</name>
		<yomi>naooki</yomi>
	</fatherInLaw>
	<altName>
		<main>主税</main>
		<first>虎八</first>
		<other>満八</other>
	</altName>
	<profiles>
			<event>
				<start>1758</start>
				<end>1773</end>
				<title>肥前蓮池藩六代藩主</title>
			</event>
			<event>
				<start>1762</start>
				<title>従五位下</title>
			</event>
			<event>
				<start>1762</start>
				<title>摂津守</title>
			</event>
	</profiles>
	<firstWife>
		<name></name>
		<fatherInLaw>
			<role>肥前佐賀藩六代藩主</role>
			<name>鍋島宗教</name>
			<yomi>munenori</yomi>
		</fatherInLaw>
		<father>
			<role>権大納言</role>
			<name>甘露寺規長</name>
			<yomi>norinaga</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直温</name>
				<yomi>naoharu</yomi>
				<role>肥前蓮池藩七代藩主</role>
				<birth>1766</birth>
				<death>1825</death>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島直温</name>
	<yomi>naoharu</yomi>
	<role>肥前蓮池藩七代藩主</role>
	<birth>1766</birth>
	<death>1825</death>
	<father>
		<role>肥前蓮池藩六代藩主</role>
		<name>鍋島直寛</name>
		<yomi>naohiro</yomi>
	</father>
	<altName>
		<main>直三郎</main>
		<first>常丸</first>
		<other>直侯</other>
	</altName>
	<profiles>
		<event>
			<start>1774</start>
			<end>1816</end>
			<title>肥前蓮池藩七代藩主</title>
		</event>
		<event>
			<start>1782</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1782</start>
			<title>甲斐守</title>
		</event>
	</profiles>
	<firstWife>
		<name>鍋島綏子</name>
		<fatherInLaw>
			<role>肥前佐賀藩八代藩主</role>
			<name>鍋島治茂</name>
			<yomi>harushige</yomi>
		</fatherInLaw>
		<father>
			<role>参議</role>
			<name>堀河康実</name>
			<yomi>yasuzane</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直道</name>
				<yomi>naomichi</yomi>
				<birth>1789</birth>
				<death>1820</death>
				<adopted>養子</adopted>
			</son>
			<son>
				<order>2</order>
				<name>鍋島直与</name>
				<yomi>naotomo</yomi>
				<role>肥前蓮池藩八代藩主</role>
				<birth>1798</birth>
				<death>1864</death>
				<adopted>養子</adopted>
			</son>
			<son>
				<order>3</order>
				<name>鍋島与善</name>
				<yomi>tomoyosi</yomi>
				<birth>1811</birth>
				<death>1839</death>
				<adopted>養子</adopted>
			</son>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島直与</name>
	<yomi>naotomo</yomi>
	<role>肥前蓮池藩八代藩主</role>
	<birth>1798</birth>
	<death>1864</death>
	<father>
		<role>肥前佐賀藩八代藩主</role>
		<name>鍋島治茂</name>
		<yomi>harushige</yomi>
	</father>
	<fatherInLaw>
		<name>神代直興</name>
	</fatherInLaw>
	<fatherInLaw>
		<role>肥前蓮池藩七代藩主</role>
		<name>鍋島直温</name>
		<yomi>naoharu</yomi>
	</fatherInLaw>
	<altName>
		<main>摂津守</main>
		<first>愛吉</first>
		<other>贈正四位</other>
	</altName>
	<profiles>
		<event>
			<start>1816</start>
			<end>1845</end>
			<title>肥前蓮池藩八代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<name>日野姷子</name>
		<father>
			<role>権大納言</role>
			<name>日野資矩</name>
			<yomi>sukenori</yomi>
		</father>
	</firstWife>
	<nextWife>
		<name>二条遂子</name>
		<father>
			<role>左大臣</role>
			<name>二条治孝</name>
			<yomi>harutaka</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直紀</name>
				<yomi>naotada</yomi>
				<role>肥前蓮池藩九代藩主</role>
				<birth>1826</birth>
				<death>1891</death>
			</son>
			<son>
				<order>2</order>
				<name>藤珎彦</name>
				<birth>1835</birth>
				<death>1886</death>
			</son>
			<daughter>
				<order>3</order>
				<name>藹子</name>
				<birth>1843</birth>
				<death>1930</death>
				<fatherInLaw>
					<role>肥前佐賀藩十代藩主</role>
					<name>鍋島直正</name>
					<altName>
						<main>閑叟</main>
					</altName>
				</fatherInLaw>
				<husband>
					<role>肥前鹿島藩十一代藩主</role>
					<name>鍋島直彬</name>
					<yomi>naoakira</yomi>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>千代</name>
				<birth>1844</birth>
				<husband>
					<name>鍋島茂彬</name>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>綱子</name>
				<birth>1851</birth>
				<death>1891</death>
				<fatherInLaw>
					<role>肥前佐賀藩十代藩主</role>
					<name>鍋島直正</name>
					<altName>
						<main>閑叟</main>
					</altName>
				</fatherInLaw>
				<husband>
					<role>対馬府中藩十六代藩主</role>
					<name>宗重正</name>
				</husband>
			</daughter>
			<daughter>
				<order>6</order>
				<name>敏子</name>
				<birth>1852</birth>
				<husband>
					<role>下野黒羽藩十六代藩主</role>
					<name>大関増勤</name>
				</husband>
			</daughter>
		</children>
	</nextWife>
</hansyu>
<hansyu>
	<name>鍋島直紀</name>
	<yomi>naotada</yomi>
	<role>肥前蓮池藩九代藩主</role>
	<birth>1826</birth>
	<death>1891</death>
	<father>
		<role>肥前蓮池藩八代藩主</role>
		<name>鍋島直与</name>
		<yomi>naotomo</yomi>
	</father>
	<altName>
		<first>直統</first>
		<other>統丸</other>
		<other>統太郎</other>
	</altName>
	<profiles>
		<event>
			<start>1845</start>
			<end>1869</end>
			<title>肥前蓮池藩九代藩主</title>
		</event>
		<event>
			<start>1869</start>
			<end>1871</end>
			<title>蓮池藩知事</title>
		</event>
		<event>
			<title>甲斐守</title>
		</event>
		<event>
			<title>従五位下</title>
		</event>
	</profiles>
	<firstWife>
		<name>鍋島常子</name>
		<father>
			<role>肥前小城藩九代藩主</role>
			<name>鍋島直堯</name>
			<yomi>naotaka</yomi>
		</father>
	</firstWife>
	<nextWife>
		<name>鍋島易</name>
		<fatherInLaw>
			<role>肥前佐賀藩十代藩主</role>
			<name>鍋島直正</name>
			<altName>
				<main>閑叟</main>
			</altName>
		</fatherInLaw>
		<father>
			<role>肥前鹿島藩八代藩主</role>
			<name>鍋島直永</name>
			<yomi>naonaga</yomi>
		</father>
		<children>
			<son>
				<order>4</order>
				<name>松平乗長</name>
				<yomi>norinaga</yomi>
				<birth>1868</birth>
				<death>1928</death>
				<description>松平氏へ</description>
			</son>
			<son>
				<order>7</order>
				<name>鍋島直柔</name>
				<yomi>naoyawa</yomi>
				<role>肥前蓮池藩十代藩主</role>
				<birth>1858</birth>
				<death>1910</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>1</order>
				<name>輝子</name>
				<birth>1857</birth>
				<death>1922</death>
				<husband>
					<role>肥前蓮池藩十代藩主</role>
					<role>子爵</role>
					<name>鍋島直柔</name>
				</husband>
			</daughter>
			<daughter>
				<order>2</order>
				<name>篤子</name>
				<birth>1867</birth>
				<death>1941</death>
				<fatherInLaw>
					<role>侯爵</role>
					<name>鍋島直大</name>
					<yomi>naohiro</yomi>
				</fatherInLaw>
				<husband>
					<role>伯爵</role>
					<name>阿部正桓</name>
					<yomi>masatake</yomi>
				</husband>
			</daughter>
			<daughter>
				<order>3</order>
				<name>親子</name>
				<birth>1868</birth>
				<death>1940</death>
				<husband>
					<role>子爵</role>
					<name>大久保教正</name>
					<yomi>noromasa</yomi>
					<altName>
						<main>鍋島熊太郎</main>
					</altName>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>常子</name>
				<birth>1870</birth>
				<death>1932</death>
				<fatherInLaw>
					<role>子爵</role>
					<name>鍋島直彬</name>
				</fatherInLaw>
				<husband>
					<role>伯爵</role>
					<name>井伊直憲</name>
					<yomi>naonori</yomi>
				</husband>
			</daughter>
			<daughter>
				<order>6</order>
				<name>孝子</name>
				<birth>1879</birth>
				<husband>
					<role>子爵</role>
					<name>本庄宗義</name>
					<yomi>muneyoshi</yomi>
				</husband>
			</daughter>
		</children>
	</nextWife>
</hansyu>
<hansyu>
	<name>鍋島直柔</name>
	<yomi>naoyawa</yomi>
	<role>肥前蓮池藩十代藩主</role>
	<birth>1858</birth>
	<death>1910</death>
	<father>
		<role>肥前佐賀藩十代藩主</role>
		<name>鍋島直正</name>
		<yomi>kansou</yomi>
		<altName>
			<main>閑叟</main>
		</altName>
	</father>
	<fatherInLaw>
		<role>肥前蓮池藩九代藩主</role>
		<name>鍋島直紀</name>
		<yomi>naotada</yomi>
	</fatherInLaw>
	<profiles>
		<event>
			<start>1884</start>
			<end>1910</end>
			<title>子爵</title>
		</event>
		<event>
			<title>貴族院議員</title>
		</event>
	</profiles>
	<firstWife>
		<name>鍋島輝子</name>
		<father>
			<role>肥前蓮池藩九代藩主</role>
			<name>鍋島直紀</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直和</name>
				<yomi>naokazu</yomi>
				<role>肥前蓮池藩十一代藩主</role>
				<birth>1884</birth>
				<death>1943</death>
			</son>
			<son>
				<order>2</order>
				<name>堀田正恒</name>
				<yomi>masatsune</yomi>
				<birth>1887</birth>
				<death>1951</death>
				<description>堀田氏へ</description>
			</son>
			<son>
				<order>4</order>
				<name>葉室直躬</name>
				<birth>1895</birth>
				<death>1971</death>
				<description>葉室家へ</description>
			</son>
			<daughter>
				<order>3</order>
				<name>教子</name>
				<birth>1892</birth>
				<death>1919</death>
				<husband>
					<role>男爵</role>
					<name>鍋島貞次郎</name>
					<yomi>sadajiro</yomi>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>文子</name>
				<husband>
					<name>三島弥彦</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島直和</name>
	<yomi>naokazu</yomi>
	<role>肥前蓮池藩十一代藩主</role>
	<role>陸軍歩兵少佐</role>
	<birth>1884</birth>
	<death>1943</death>
	<father>
		<role>肥前蓮池藩十代藩主</role>
		<role>子爵</role>
		<name>鍋島直柔</name>
		<yomi>naoyawa</yomi>
	</father>
	<profiles>
		<event>
			<start>1910</start>
			<end>1943</end>
			<title>子爵</title>
		</event>
	</profiles>
	<firstWife>
		<name>松平貞子</name>
		<father>
			<role>伯爵</role>
			<name>松平直亮</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直方</name>
				<yomi>naokata</yomi>
				<role>肥前蓮池藩十二代藩主</role>
				<birth>1906</birth>
				<death>1939</death>
			</son>
			<daughter>
				<order>2</order>
				<name>絢子</name>
				<birth>1908</birth>
				<husband>
					<role>子爵</role>
					<name>織田長利</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>松平益子</name>
		<father>
			<role>伯爵</role>
			<name>松平直亮</name>
		</father>
		<children>
			<son>
				<order>3</order>
				<name>鍋島直誠</name>
				<birth>1922</birth>
				<death>1950</death>
			</son>
			<daughter>
				<order>1</order>
				<name>花子</name>
				<birth>1911</birth>
				<husband>
					<role>子爵</role>
					<name>梅小路定雄</name>
				</husband>
			</daughter>
			<daughter>
				<order>2</order>
				<name>峯子</name>
				<birth>1913</birth>
				<husband>
					<name>細川立暢</name>
					<yomi>tatsunaga</yomi>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>重子</name>
				<birth>1924</birth>
				<husband>
					<name>松原庸雄</name>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>宣子</name>
				<birth>1927</birth>
				<death>1950</death>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島直方</name>
	<yomi>naokata</yomi>
	<role>肥前蓮池藩十二代藩主</role>
	<birth>1906</birth>
	<death>1939</death>
	<father>
		<role>肥前蓮池藩十一代藩主</role>
		<role>子爵</role>
		<name>鍋島直和</name>
		<yomi>naokazu</yomi>
	</father>
	<firstWife>
		<name>一条圭子</name>
		<father>
			<role>公爵</role>
			<name>一条実輝</name>
			<yomi>saneteru</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直輝</name>
				<yomi>naoteru</yomi>
				<role>肥前蓮池藩十三代藩主</role>
				<birth>1937</birth>
			</son>
			<daughter>
				<order>2</order>
				<name>玲子</name>
				<birth>1938</birth>
				<husband>
					<name>高瀬一重</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島直輝</name>
	<yomi>naoteru</yomi>
	<role>肥前蓮池藩十三代藩主</role>
	<birth>1937</birth>
	<father>
		<role>肥前蓮池藩十二代藩主</role>
		<name>鍋島直方</name>
		<yomi>naokata</yomi>
	</father>
	<profiles>
			<event>
				<start>1943</start>
				<end>1947</end>
				<title>子爵</title>
			</event>
	</profiles>
	<firstWife>
		<name>中部直子</name>
		<birth>1943</birth>
		<father>
			<name>中部義吉</name>
		</father>
	</firstWife>
	<secondWife>
		<name>岡崎寿美子</name>
		<birth>1937</birth>
		<father>
			<name>岡崎実太</name>
		</father>
		<children>
			<son>
				<order>2</order>
				<name>鍋島直弘</name>
				<birth>1973</birth>
			</son>
			<daughter>
				<order>1</order>
				<name>典子</name>
				<birth>1964</birth>
			</daughter>
			<daughter>
				<order>3</order>
				<name>由理子</name>
				<birth>1974</birth>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<haichaku>
	<name>鍋島与善</name>
	<yomi>tomoyosi</yomi>
	<birth>1811</birth>
	<death>1839</death>
	<father>
		<role>肥前蓮池藩世嗣</role>
		<name>鍋島直道</name>
		<yomi>naomiti</yomi>
	</father>
	<fatherInLaw>
		<role>肥前蓮池藩七代藩主</role>
		<name>鍋島直温</name>
		<yomi>naoharu</yomi>
	</fatherInLaw>
	<altName>
		<first>敬之助</first>
	</altName>
	<firstWife>
		<name></name>
	</firstWife>
</haichaku>
<haichaku>
	<name>鍋島直道</name>
	<yomi>naomichi</yomi>
	<birth>1789</birth>
	<death>1820</death>
	<father>
		<role>肥前佐賀藩八代藩主</role>
		<name>鍋島治茂</name>
		<yomi>harushige</yomi>
	</father>
	<fatherInLaw>
		<role>肥前蓮池藩七代藩主</role>
		<name>鍋島直温</name>
		<yomi>naoharu</yomi>
	</fatherInLaw>
	<altName>
		<main>下総</main>
	</altName>
	<profiles>
			<event>
				<title>肥前蓮池藩世嗣</title>
			</event>
			<event>
				<start>1815</start>
				<title>廃嫡</title>
			</event>
	</profiles>
	<firstWife>
		<name></name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島与善</name>
				<yomi>tomoyosi</yomi>
				<birth>1811</birth>
				<death>1839</death>
			</son>
		</children>
	</firstWife>
</haichaku>
</hasuikeNabeshima>