<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE honNabeshima [
<!ELEMENT honNabeshima (hansyu+)>
<!ELEMENT hansyu (name*, yomi*, role*, birth*, death*, father*, fatherInLaw*, grfather*, mother*, grMother*, altName*, profiles*, firstWife*, nextWife*, secondWife*)>
<!ELEMENT father (role*, name*, yomi*, altName*)>
<!ELEMENT fatherInLaw (role*, name*, yomi*, altName*)>
<!ELEMENT grFather (role*, name*, yomi*, altName*)>
<!ELEMENT mother (role*, name*, yomi*, altName*)>
<!ELEMENT grMother (role*, name*, yomi*, altName*)>
<!ELEMENT altName (main*, first*, other*)>
<!ELEMENT profiles (event+)>
<!ELEMENT event (start*, end*, title)>
<!ELEMENT firstWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT nextWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT secondWife (name*, birth*, death*, fatherInLaw*, father*, brother*, children*)>
<!ELEMENT children (son*, daughter*)>
<!ELEMENT son (order, name*, yomi*, altName*, role*, birth*, death*, father*, mother*, fatherInLaw*, wife*, fiance*, description*, adopted*)>
<!ELEMENT daughter (order, name*, yomi*, altName*, birth*, death*, father*, mother*, fatherInLaw*, husband*, fiance*, description*,adopted*)>
<!ELEMENT husband (role*, name*, birth*, death*, father*, mother*)>
<!ELEMENT wife (role*, name*, birth*, death*, father*, mother*)>
<!ELEMENT brother (role*, name*, birth*, death*, father*, mother*)>
<!ELEMENT fiance (role*, name*, birth*, death*, father*, mother*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT yomi (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT birth (#PCDATA)>
<!ELEMENT death (#PCDATA)>
<!ELEMENT main (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT other (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT adopted (#PCDATA)>
]>

<honNabeshima>
<hansyu>
	<name>鍋島清久</name>
	<yomi>kiyohisa</yomi>
	<birth>1490</birth>
	<death>1544</death>
	<father>
		<name>鍋島経房</name>
	</father>
	<firstWife>
		<name></name>
		<father>
			<name>野田大隈守</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島清泰</name>
			</son>
			<son>
				<order>2</order>
				<name>鍋島清房</name>
				<yomi>kiyofusa</yomi>
				<role>駿河守</role>
				<birth>1513</birth>
				<death>？</death>
			</son>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島清房</name>
	<yomi>kiyofusa</yomi>
	<role>駿河守</role>
	<birth>1513</birth>
	<death>？</death>
	<father>
		<name>鍋島清久</name>
		<yomi>kiyohisa</yomi>
	</father>
	<altName>
		<first>孫四郎</first>
	</altName>
	<profiles>
		<event>
			<title>駿河守</title>
		</event>
	</profiles>
	<firstWife>
		<name></name>
		<father>
			<role>肥前水ヶ江城主</role>
			<name>龍造寺家純</name>
			<yomi>iesumi</yomi>
		</father>
	</firstWife>
	<nextWife>
		<name>慶闇尼</name>
		<father>
			<name>龍造寺胤和</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島信房</name>
				<birth>1529</birth>
				<death>1609</death>
			</son>
			<son>
				<order>2</order>
				<name>鍋島直茂</name>
				<yomi>naoshige</yomi>
				<role>肥前佐賀領主</role>
				<birth>1538</birth>
				<death>1618</death>
			</son>
			<son>
				<order>3</order>
				<name>小河信俊</name>
			</son>
		</children>
	</nextWife>
</hansyu>
<hansyu>
	<name>鍋島直茂</name>
	<yomi>naoshige</yomi>
	<role>肥前佐賀領主</role>
	<birth>1538</birth>
	<death>1618</death>
	<father>
		<role>駿河守</role>
		<name>鍋島清房</name>
		<yomi>kiyofusa</yomi>
	</father>
	<fatherInLaw>
		<name>龍造寺政家</name>
	</fatherInLaw>
	<altName>
		<first>彦法師丸</first>
		<other>信安</other>
		<other>信真</other>
		<other>信昌</other>
		<other>信生</other>
	</altName>
	<profiles>
		<event>
			<title>孫四郎</title>
		</event>
		<event>
			<title>左衛門大夫</title>
		</event>
		<event>
			<start>1590</start>
			<end>1607</end>
			<title>肥前佐賀領主</title>
		</event>
		<event>
			<title>従五位下</title>
		</event>
		<event>
			<title>飛騨守</title>
		</event>
		<event>
			<title>加賀守</title>
		</event>
	</profiles>
	<firstWife>
		<name>慶円</name>
		<father>
			<name>高木肥前守胤秀</name>
		</father>
	</firstWife>
	<nextWife>
		<name>陽泰院</name>
		<name>彦鶴</name>
		<father>
			<name>石井兵部少輔常延</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島勝茂</name>
				<yomi>katsushige</yomi>
				<role>肥前佐賀藩初代藩主</role>
				<birth>1580</birth>
				<death>1627</death>
			</son>
			<son>
				<order>2</order>
				<name>鍋島忠茂</name>
				<yomi>tadashige</yomi>
				<birth>1584</birth>
				<death>1624</death>
				<description>忠茂家系へ</description>
			</son>
			<daughter>
				<order>3</order>
				<name>伊勢龍</name>
				<husband>
					<name>鍋島茂里</name>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>千鶴</name>
				<husband>
					<name>多久安順</name>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>長寿院</name>
				<name>彦菊</name>
				<husband>
					<role>二代諫早領主</role>
					<name>諫早直孝</name>
				</husband>
			</daughter>
		</children>
	</nextWife>
	<secondWife>
		<name></name>
		<brother>
			<name>井手口小左衛門</name>
		</brother>
		<children>
			<son>
				<order>1</order>
				<name>龍造寺高房</name>
				<yomi>takafusa</yomi>
				<birth>1586</birth>
				<death>1607</death>
				<adopted>養子</adopted>
			</son>
			<son>
				<order>2</order>
				<name>鍋島茂里</name>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>3</order>
				<name>瑞光院</name>
				<father>
					<name>鍋島茂里</name>
				</father>
				<husband>
					<role>肥前佐賀藩主</role>
					<name>龍造寺高房</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<husband>
					<name>大田茂連</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島勝茂</name>
	<yomi>katsushige</yomi>
	<role>肥前佐賀藩初代藩主</role>
	<birth>1580</birth>
	<death>1657</death>
	<father>
		<role>肥前佐賀領主</role>
		<name>鍋島直茂</name>
		<yomi>naoshige</yomi>
	</father>
	<altName>
		<first>信茂</first>
		<other>清茂</other>
		<other>伊平太</other>
	</altName>
	<profiles>
		<event>
			<start>1595</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1595</start>
			<title>信濃守</title>
		</event>
		<event>
			<start>1607</start>
			<end>1657</end>
			<title>肥前佐賀藩初代藩主</title>
		</event>
		<event>
			<start>1626</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1626</start>
			<title>侍従</title>
		</event>
	</profiles>
	<firstWife>
		<name></name>
		<fatherInLaw>
			<role>関白</role>
			<name>豊臣秀吉</name>
			<yomi>hideyoshi</yomi>
		</fatherInLaw>
		<father>
			<name>戸田勝隆</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>伊勢松</name>
			</son>
		</children>
	</firstWife>
	<nextWife>
		<name>高源院</name>
		<name>菊姫</name>
		<fatherInLaw>
			<role>征夷大将軍</role>
			<name>徳川家康</name>
		</fatherInLaw>
		<father>
			<role>美濃大垣藩初代藩主</role>
			<name>岡部長盛</name>
			<yomi>nagamori</yomi>
		</father>
		<children>
			<son>
				<order>3</order>
				<name>満千代</name>
			</son>
			<son>
				<order>4</order>
				<name>鍋島忠直</name>
				<role>肥前守</role>
				<birth>1613</birth>
				<death>1635</death>
			</son>
			<son>
				<order>5</order>
				<name>鍋島直澄</name>
				<birth>1616</birth>
				<death>1669</death>
				<description>肥前蓮池藩へ</description>
			</son>
			<son>
				<order>7</order>
				<name>鍋島直弘</name>
				<description>白石鍋島家へ</description>
			</son>
			<son>
				<order>9</order>
				<name>鍋島直朝</name>
				<birth>1622</birth>
				<death>1709</death>
				<description>肥前鹿島藩へ</description>
			</son>
			<son>
				<order>11</order>
				<name>卿公</name>
			</son>
			<son>
				<order>13</order>
				<name>神代直長</name>
				<fatherInLaw>
					<name>神代常宜</name>
				</fatherInLaw>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<role>出羽米沢藩二代藩主</role>
					<name>上杉定勝</name>
				</husband>
			</daughter>
			<daughter>
				<order>2</order>
				<name>天性院</name>
				<name>鶴</name>
				<husband>
					<name>多久茂辰</name>
				</husband>
			</daughter>
			<daughter>
				<order>6</order>
				<name>宝乗院</name>
				<husband>
					<role>三代諫早領主</role>
					<name>諫早茂敬</name>
				</husband>
			</daughter>
			<daughter>
				<order>8</order>
				<name>娘</name>
				<husband>
					<name>神代常利</name>
				</husband>
			</daughter>
			<daughter>
				<order>10</order>
				<name>娘</name>
				<husband>
					<role>肥前島原藩初代藩主</role>
					<name>松平忠房</name>
				</husband>
			</daughter>
			<daughter>
				<order>12</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前小城藩初代藩主</role>
					<name>鍋島元茂</name>
				</fatherInLaw>
				<husband>
					<name>鍋島直広</name>
				</husband>
			</daughter>
		</children>
	</nextWife>
	<secondWife>
		<name>小西氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島元茂</name>
				<birth>1602</birth>
				<death>1654</death>
				<description>肥前小城藩へ</description>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>松吉</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>彦太郎</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>超誉</name>
			</son>
			<daughter>
				<order>2</order>
				<name>南祥院</name>
				<name>鶴子</name>
				<father>
					<name>多久茂辰</name>
				</father>
				<husband>
					<role>肥前小城藩二代藩主</role>
					<name>鍋島直能</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>3</order>
				<name>彦宮</name>
				<father>
					<role>二代諫早領主</role>
					<name>諫早直孝</name>
				</father>
				<husband>
					<name>鍋島常貞</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<!--
<hansyu>
	<name>鍋島忠直</name>
	<yomi>tadanao</yomi>
	<birth>1613</birth>
	<death>1635</death>
	<father>
		<role>肥前佐賀藩初代藩主</role>
		<name>鍋島勝茂</name>
		<yomi>katsushige</yomi>
	</father>
	<altName>
		<first>翁助</first>
	</altName>
	<profiles>
		<event>
			<start>1622</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1622</start>
			<title>肥前守</title>
		</event>
	</profiles>
	<firstWife>
		<name></name>
		<father>
			<role>播磨姫路藩主</role>
			<name>松平忠明</name>
			<yomi>tadaakira</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島光茂</name>
				<birth>1632</birth>
				<death>1700</death>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
		</children>
	</firstWife>
</hansyu>
-->
<hansyu>
	<name>鍋島光茂</name>
	<yomi>mitsushige</yomi>
	<birth>1632</birth>
	<death>1700</death>
	<father>
		<role>肥前守</role>
		<name>鍋島忠直</name>
		<yomi>tadanao</yomi>
	</father>
	<altName>
		<first>翁助</first>
	</altName>
	<profiles>
		<event>
			<start>1648</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1648</start>
			<title>丹後守</title>
		</event>
		<event>
			<start>1657</start>
			<end>1695</end>
			<title>肥前佐賀藩二代藩主</title>
		</event>
		<event>
			<start>1658</start>
			<title>侍従</title>
		</event>
	</profiles>
	<firstWife>
		<name>虎</name>
		<father>
			<role>出羽米沢藩二代藩主</role>
			<name>上杉定勝</name>
			<yomi>sadakatsu</yomi>
		</father>
		<children>
			<son>
				<order>2</order>
				<name>鍋島綱茂</name>
				<role>肥前佐賀藩三代藩主</role>
				<birth>1652</birth>
				<death>1707</death>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<role>下総古河藩三代藩主</role>
					<name>土井利重</name>
				</husband>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<husband>
					<role>信濃松本藩三代藩主</role>
					<name>水野忠直</name>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<husband>
					<role>日向飫肥藩五代藩主</role>
					<name>伊東祐実</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>中院甘</name>
		<father>
			<role>権大納言</role>
			<name>中院通純</name>
			<yomi>michizumi</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島吉茂</name>
				<role>肥前佐賀藩四代藩主</role>
				<birth>1664</birth>
				<death>1730</death>
			</son>
			<son>
				<order>2</order>
				<name>某</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<name>鍋島武興</name>
				</fatherInLaw>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>鍋島直朗</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>執行氏</name>
		<children>
			<son>
				<order>4</order>
				<name>三平</name>
			</son>
			<son>
				<order>5</order>
				<name>左内</name>
			</son>
			<son>
				<order>7</order>
				<name>亀千代</name>
			</son>
			<son>
				<order>8</order>
				<name>伊平太</name>
			</son>
			<son>
				<order>9</order>
				<name>辰茂</name>
			</son>
			<son>
				<order>13</order>
				<name>鍋島宗茂</name>
				<role>肥前佐賀藩五代藩主</role>
				<birth>1687</birth>
				<death>1755</death>
			</son>
			<son>
				<order>15</order>
				<name>茂之</name>
				<fatherInLaw>
					<name>鍋島清信</name>
				</fatherInLaw>
			</son>
			<son>
				<order>16</order>
				<name>徳寛</name>
			</son>
			<son>
				<order>17</order>
				<name>神代直方</name>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<name>鍋島嵩就</name>
				</fatherInLaw>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩三代藩主</role>
					<name>鍋島綱茂</name>
				</fatherInLaw>
				<husband>
					<role>播磨姫路藩初代藩主</role>
					<name>榊原政邦</name>
				</husband>
			</daughter>
			<daughter>
				<order>6</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>10</order>
				<name>娘</name>
				<husband>
					<name>鍋島直愈</name>
				</husband>
			</daughter>
			<daughter>
				<order>11</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>12</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>14</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>18</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩四代藩主</role>
					<name>鍋島吉茂</name>
				</fatherInLaw>
				<husband>
					<name>岡部盛明</name>
				</husband>
			</daughter>
			<daughter>
				<order>19</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>20</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>多久茂文</name>
				<birth>1669</birth>
				<death>1711</death>
				<description>多久氏へ</description>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>諫早茂照</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>彦法師</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>真木氏</name>
		<children>
			<son>
				<order>1</order>
				<name>村田政盛</name>
				<fatherInLaw>
					<name>村田政種</name>
				</fatherInLaw>
			</son>
			<son>
				<order>2</order>
				<name>鍋島長行</name>
				<birth>1675</birth>
				<death>1738</death>
				<description>忠茂家系へ</description>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>村山氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>鍋島茂正</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>斎藤氏</name>
		<children>
			<son>
				<order>1</order>
				<name>久松</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<children>
			<son>
				<order>2</order>
				<name>百助</name>
			</son>
			<daughter>
				<order>1</order>
				<name>某氏</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>岡本氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩四代藩主</role>
					<name>鍋島吉茂</name>
				</fatherInLaw>
				<husband>
					<role>肥前蓮池藩四代藩主</role>
					<name>鍋島直恒</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>鳥巣氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>戸田氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>須古氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>松太郎</name>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<father>
					<role>肥前蓮池藩初代藩主</role>
					<name>鍋島直澄</name>
				</father>
				<husband>
					<role>肥前鹿島藩二代藩主</role>
					<name>鍋島直条</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<father>
					<role>肥前小城藩二代藩主</role>
					<name>鍋島直能</name>
				</father>
				<husband>
					<role>三河刈谷藩初代藩主</role>
					<name>三浦明敬</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<father>
					<name>榊原照清</name>
				</father>
				<husband>
					<role>肥前蓮池藩二代藩主</role>
					<name>鍋島直之</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島綱茂</name>
	<yomi>tsunashige</yomi>
	<birth>1652</birth>
	<death>1707</death>
	<father>
		<role>肥前佐賀藩二代藩主</role>
		<name>鍋島光茂</name>
		<yomi>mitsushige</yomi>
	</father>
	<altName>
		<first>左衛門佐</first>
	</altName>
	<profiles>
		<event>
			<start>1667</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1667</start>
			<title>信濃守</title>
		</event>
		<event>
			<start>1695</start>
			<end>1707</end>
			<title>肥前佐賀藩三代藩主</title>
		</event>
		<event>
			<start>1695</start>
			<title>侍従</title>
		</event>
	</profiles>
	<firstWife>
		<name>布与</name>
		<father>
			<role>越前福井藩二代藩主</role>
			<name>松平光通</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島吉茂</name>
				<role>肥前佐賀藩四代藩主</role>
				<birth>1664</birth>
				<death>1730</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<father>
					<role>肥前佐賀藩二代藩主</role>
					<name>鍋島光茂</name>
				</father>
				<husband>
					<role>播磨姫路藩初代藩主</role>
					<name>榊原政邦</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<father>
					<name>小花成武</name>
				</father>
				<husband>
					<role>肥前蓮池藩三代藩主</role>
					<name>鍋島直称</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<son>
				<order>1</order>
				<name>千太郎</name>
				<fatherInLaw>
					<name>神代直長</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>田中氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<fiance>
					<name>上杉吉憲</name>
				</fiance>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島吉茂</name>
	<yomi>yoshishige</yomi>
	<birth>1664</birth>
	<death>1730</death>
	<father>
		<role>肥前佐賀藩二代藩主</role>
		<name>鍋島光茂</name>
		<yomi>mitsushige</yomi>
	</father>
	<fatherInLaw>
		<name>神代某</name>
	</fatherInLaw>
	<fatherInLaw>
		<role>肥前佐賀藩三代藩主 </role>
		<name>鍋島綱茂</name>
		<yomi>tsunashige</yomi>
	</fatherInLaw>
	<altName>
		<main>弾正</main>
		<first>矩茂</first>
		<other>神代直利</other>
	</altName>
	<profiles>
		<event>
			<start>1706</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1706</start>
			<title>左衛門佐</title>
		</event>
		<event>
			<start>1707</start>
			<end>1730</end>
			<title>肥前佐賀藩四代藩主</title>
		</event>
		<event>
			<start>1707</start>
			<title>丹後守</title>
		</event>
		<event>
			<start>1707</start>
			<title>侍従</title>
		</event>
	</profiles>
	<firstWife>
		<name>土</name>
		<father>
			<name>神代直長</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島宗茂</name>
				<role>肥前佐賀藩五代藩主</role>
				<birth>1687</birth>
				<death>1755</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<father>
					<role>肥前蓮池藩三代藩主</role>
					<name>鍋島直称</name>
				</father>
				<husband>
					<role>権大納言</role>
					<name>日野資時</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<father>
					<role>肥前佐賀藩二代藩主</role>
					<name>鍋島光茂</name>
				</father>
				<husband>
					<name>岡部盛明</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<father>
					<role>肥前小城藩三代藩主</role>
					<name>鍋島元武</name>
				</father>
				<husband>
					<role>三河刈谷藩二代藩主</role>
					<name>三浦明喬</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>5</order>
				<name>娘</name>
				<father>
					<role>肥前佐賀藩二代藩主</role>
					<name>鍋島光茂</name>
				</father>
				<husband>
					<role>肥前蓮池藩四代藩主</role>
					<name>鍋島直恒</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</firstWife>
</hansyu>
<hansyu>
	<name>鍋島宗茂</name>
	<yomi>muneshige</yomi>
	<birth>1687</birth>
	<death>1755</death>
	<father>
		<role>肥前佐賀藩二代藩主</role>
		<name>鍋島光茂</name>
		<yomi>mitsushige</yomi>
	</father>
	<fatherInLaw>
		<role>肥前佐賀藩四代藩主</role>
		<name>鍋島吉茂</name>
		<yomi>yoshishige</yomi>
	</fatherInLaw>
	<altName>
		<main>主膳</main>
		<first>直董</first>
	</altName>
	<profiles>
		<event>
			<start>1716</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1716</start>
			<title>信濃守</title>
		</event>
		<event>
			<start>1730</start>
			<end>1738</end>
			<title>肥前佐賀藩五代藩主</title>
		</event>
		<event>
			<start>1730</start>
			<title>侍従</title>
		</event>
		<event>
			<start>1751</start>
			<title>飛騨守</title>
		</event>
	</profiles>
	<firstWife>
		<name>久世貞</name>
		<father>
			<role>権大納言</role>
			<name>久世通夏</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島宗教</name>
				<role>肥前佐賀藩六代藩主</role>
				<birth>1718</birth>
				<death>1780</death>
			</son>
			<son>
				<order>3</order>
				<name>鍋島直鄰</name>
			</son>
			<son>
				<order>4</order>
				<name>鍋島重茂</name>
				<role>肥前佐賀藩七代藩主</role>
				<birth>1733</birth>
				<death>1770</death>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>有田氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>成富氏</name>
		<children>
			<son>
				<order>1</order>
				<name>某</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>石井氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>古賀氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<children>
			<son>
				<order>2</order>
				<name>某</name>
			</son>
			<daughter>
				<order>1</order>
				<name>某氏</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<children>
			<son>
				<order>2</order>
				<name>某</name>
			</son>
			<daughter>
				<order>1</order>
				<name>某氏</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>小代氏</name>
		<children>
			<son>
				<order>1</order>
				<name>竹丸</name>
			</son>
			<son>
				<order>3</order>
				<name>甚吉</name>
			</son>
			<son>
				<order>4</order>
				<name>翁助</name>
			</son>
			<son>
				<order>6</order>
				<name>鍋島治茂</name>
				<role>肥前佐賀藩八代藩主</role>
				<birth>1745</birth>
				<death>1805</death>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<death>1789</death>
				<husband>
					<role>伊予宇和島藩五代藩主甚吉</role>
					<name>伊達村候</name>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>娘</name>
				<death>1789</death>
				<husband>
					<role>和泉岸和田藩六代藩主</role>
					<name>岡部長住</name>
				</husband>
			</daughter>
			<daughter>
				<order>7</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>8</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島宗教</name>
	<yomi>munenori</yomi>
	<birth>1718</birth>
	<death>1780</death>
	<father>
		<role>肥前佐賀藩五代藩主</role>
		<name>鍋島宗茂</name>
		<yomi>muneshige</yomi>
	</father>
	<altName>
		<first>万吉</first>
		<other>教茂</other>
	</altName>
	<profiles>
		<event>
			<start>1732</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1732</start>
			<title>丹後守</title>
		</event>
		<event>
			<start>1738</start>
			<end>1760</end>
			<title>肥前佐賀藩六代藩主</title>
		</event>
		<event>
			<start>1738</start>
			<title>侍従</title>
		</event>
		<event>
			<title>婚約者：（父：因幡鳥取藩三代藩主 池田吉泰）</title>
		</event>
	</profiles>
	<firstWife>
		<name>中院綱</name>
		<father>
			<role>右大臣</role>
			<name>中院通躬</name>
			<yomi>michimi</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島重茂</name>
				<yomi>shigemochi</yomi>
				<role>肥前佐賀藩七代藩主</role>
				<birth>1733</birth>
				<death>1770</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<father>
					<role>権大納言</role>
					<name>五条為範</name>
				</father>
				<husband>
					<role>肥前小城藩六代藩主</role>
					<name>鍋島直員</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<father>
					<role>権大納言</role>
					<name>甘露寺規長</name>
				</father>
				<husband>
					<role>肥前蓮池藩六代藩主</role>
					<name>鍋島直寛</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>中村氏</name>
		<children>
			<son>
				<order>1</order>
				<name>吉次郎</name>
			</son>
		</children>
	</secondWife>
	<secondWife>
		<name>池田氏</name>
		<children>
			<son>
				<order>1</order>
				<name>富松</name>
			</son>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島重茂</name>
	<yomi>shigemochi</yomi>
	<birth>1733</birth>
	<death>1770</death>
	<father>
		<role>肥前佐賀藩五代藩主</role>
		<name>鍋島宗茂</name>
		<yomi>muneshige</yomi>
	</father>
	<fatherInLaw>
		<role>肥前佐賀藩六代藩主 </role>
		<name>鍋島宗教</name>
		<yomi>munenori</yomi>
	</fatherInLaw>
	<altName>
		<first>捨丸</first>
		<other>直亮</other>
		<other>右平太</other>
	</altName>
	<profiles>
		<event>
			<start>1749</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1749</start>
			<title>上総介</title>
		</event>
		<event>
			<start>1760</start>
			<end>1770</end>
			<title>肥前佐賀藩七代藩主</title>
		</event>
		<event>
			<start>1760</start>
			<title>信濃守</title>
		</event>
		<event>
			<title>侍従</title>
		</event>
	</profiles>
	<firstWife>
		<name>源</name>
		<father>
			<role>陸奥仙台藩六代藩主</role>
			<name>伊達宗村</name>
			<yomi>munemura</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>源丸</name>
			</son>
		</children>
	</firstWife>
	<nextWife>
		<name>淑姫</name>
		<father>
			<role>田安徳川家初代当主</role>
			<name>徳川宗武</name>
			<yomi>munetakeb</yomi>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島治茂</name>
				<role>肥前佐賀藩八代藩主</role>
				<birth>1745</birth>
				<death>1805</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<father>
					<role>肥前蓮池藩四代藩主</role>
					<name>鍋島直恒</name>
				</father>
				<husband>
					<role>参議</role>
					<name>堀河康実</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</nextWife>
	<secondWife>
		<name>小林氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<role>肥前小城藩七代藩主</role>
					<name>鍋島直愈</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
</hansyu>
<hansyu>
	<name>鍋島治茂</name>
	<yomi>harushige</yomi>
	<birth>1745</birth>
	<death>1805</death>
	<father>
		<role>肥前佐賀藩五代藩主</role>
		<name>鍋島宗茂</name>
		<yomi>muneshige</yomi>
	</father>
	<fatherInLaw>
		<role>肥前鹿島藩四代藩主 </role>
		<name>鍋島直郷</name>
		<yomi>naosato</yomi>
	</fatherInLaw>
	<fatherInLaw>
		<role>肥前佐賀藩七代藩主 </role>
		<name>鍋島重茂</name>
		<yomi>shigemochi</yomi>
	</fatherInLaw>
	<altName>
		<main>中務</main>
	</altName>
	<profiles>
		<event>
			<start>1763</start>
			<end>1770</end>
			<title>肥前鹿島藩五代藩主 直熙</title>
		</event>
		<event>
			<start>1763</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1763</start>
			<title>和泉守</title>
		</event>
		<event>
			<start>1770</start>
			<end>1805</end>
			<title>肥前佐賀藩八代藩主</title>
		</event>
		<event>
			<start>1770</start>
			<title>肥前守</title>
		</event>
		<event>
			<start>1770</start>
			<title>従四位下</title>
		</event>
		<event>
			<start>1771</start>
			<title>侍従</title>
		</event>
	</profiles>
	<firstWife>
		<name>中院當</name>
		<father>
			<role>権中納言</role>
			<name>中院通枝</name>
			<yomi>michieda</yomi>
		</father>
		<children>
			<daughter>
				<order>1</order>
				<name>誠</name>
				<birth>1775</birth>
				<death>1801</death>
				<husband>
					<role>越後高田藩三代藩主</role>
					<name>榊原政令</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
	<nextWife>
		<name>井伊雍</name>