<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ogiNabeshima [
<!ELEMENT ogiNabeshima (hansyu+)>
<!ELEMENT hansyu (name, yomi*, role*, birth*, death*, father*, fatherInLaw*, altName*, profiles*, firstWife*, secondWife*)>
<!ELEMENT father (role*, name*, yomi*, altName*)>
<!ELEMENT fatherInLaw (role*, name*, yomi*, altName*)>
<!ELEMENT grFather (role*, name*, yomi*, altName*)>
<!ELEMENT mother (role*, name*, yomi*, altName*)>
<!ELEMENT grMother (role*, name*, yomi*, altName*)>
<!ELEMENT altName (main*, first*, other*)>
<!ELEMENT profiles (event+)>
<!ELEMENT event (start*, end*, title)>
<!ELEMENT firstWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT nextWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT secondWife (name*, birth*, death*, fatherInLaw*, father*, children*)>
<!ELEMENT children (son*, daughter*)>
<!ELEMENT son (order, name, yomi*, altName*, role*, birth*, death*, father*, mother*, fatherInLaw*, wife*, description*, adopted*)>
<!ELEMENT daughter (order, name, yomi*, altName*, birth*, death*, father*, mother*, fatherInLaw*, husband*, adopted*)>
<!ELEMENT husband (role*, name, birth*, death*, father*, mother*)>
<!ELEMENT wife (role*, name, birth*, death*, father*, mother*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT yomi (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT birth (#PCDATA)>
<!ELEMENT death (#PCDATA)>
<!ELEMENT main (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT other (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT adopted (#PCDATA)>
]>

<ogiNabeshima>
<hansyu>
	<name>鍋島元茂</name>
	<yomi>motoshige</yomi>
	<birth>1602</birth>
	<death>1654</death>
	<father>
		<role>肥前佐賀藩初代藩主</role>
		<name>鍋島勝茂</name>
		<yomi>katsushige</yomi>
	</father>
	<altName>
		<main>月堂</main>
		<first>直元</first>
		<other>三平</other>
	</altName>
	<profiles>
		<event>
			<start>1617</start>
			<end>1654</end>
			<title>肥前小城藩初代藩主</title>
		</event>
		<event>
			<start>1619</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1619</start>
			<title>紀伊守</title>
		</event>
	</profiles>
	<firstWife>
		<name>鍋島茂里の娘</name>
		<father>
			<name>鍋島茂里</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直能</name>
				<yomi>naoyoshi</yomi>
				<role>肥前小城藩二代藩主</role>
				<birth>1623</birth>
				<death>1689</death>
			</son>
		</children>
	</firstWife>
	<secondWife>   
		<name>犬塚氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直朗</name>
				<fatherInLaw>
					<name>鍋島武興</name>
				</fatherInLaw>
			</son>
			<son>
				<order>2</order>
				<name>鍋島直治</name>
			</son>
			<daughter>
				<order>3</order>
				<name>娘</name>
				<father>
					<role>肥前佐賀藩初代藩主</role>
					<name>鍋島勝茂</name>
				</father>
				<husband>
					<name>鍋島直広</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
			<daughter>
				<order>4</order>		
				<name>娘</name>
				<father>
					<name>多久茂辰</name>
				</father>
				<husband>
					<name>岡部興貞</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直能</name>
	<yomi>naoyoshi</yomi>
	<birth>1623</birth>
	<death>1689</death>
	<father>
		<role>肥前小城藩初代藩主</role>
		<name>鍋島元茂</name>
		<yomi>motoshige</yomi>
	</father>
	<altName>
		<first>直宗</first>
		<other>飛騨</other>
		<other>飛騨守</other>
	</altName>
	<profiles>
		<event>
			<start>1651</start>
		<title>従五位下</title>
		</event>
		<event>
			<start>1651</start>
		<title>加賀守</title>
		</event>
		<event>
			<start>1654</start>
			<end>1679</end>
		<title>肥前小城藩二代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<name>鶴子</name>
		<name>南祥院</name>
		<fatherInLaw>
			<role>肥前佐賀藩初代藩主</role>
			<name>鍋島勝茂</name>
		</fatherInLaw>
		<father>
			<name>多久茂辰</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直将</name>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩二代藩主</role>
					<name>鍋島光茂</name>
				</fatherInLaw>
				<husband>
					<role>三河刈谷藩初代藩主</role>
					<name>三浦明敬</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>西川氏</name>
		<children>
			<son>
				<order>2</order>
				<name>鍋島元敦</name>
			</son>
			<son>
				<order>3</order>
				<name>晃淳</name>
				<role>僧</role>
			</son>
			<son>
				<order>4</order>
				<name>三浦能冬</name>
				<fatherInLaw>
					<name>三浦盛治</name>
				</fatherInLaw>
			</son>
			<son>
				<order>5</order>
				<name>佐膳</name>
			</son>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>田尻興種</name>
				</husband>
			</daughter>
			<daughter>
				<order>5</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>小川坊城家女</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島元武</name>
				<yomi>mototake</yomi>
				<role>肥前小城藩三代藩主</role>
				<birth>1662</birth>
				<death>1713</death>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<husband>
					<role>六代常陸松岡領主</role>
					<name>中山信敏</name>
				</husband>
				<adopted>養子</adopted>
			</daughter>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島元武</name>
	<yomi>mototake</yomi>
	<birth>1662</birth>
	<death>1713</death>
	<father>
		<role>肥前小城藩二代藩主</role>
		<name>鍋島直能</name>
		<yomi>naoyosi</yomi>
	</father>
	<altName>
		<first>直頼</first>
		<other>久丸、式部</other>
	</altName>
	<profiles>
		<event>
			<start>1676</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1676</start>
			<title>紀伊守</title>
		</event>
		<event>
			<start>1679</start>
			<end>1713</end>
			<title>肥前小城藩三代藩主</title>
		</event>
		<event>
			<start>1693</start>
			<end>1709</end>
			<title>奥詰役</title>
		</event>
	</profiles>
	<secondWife>
		<name>城島氏</name>
		<children>
			<son>
				<order>3</order>
				<name>鍋島元延</name>
				<role>肥前小城藩四代藩主</role>
				<birth>1695</birth>
				<death>1714</death>
			</son>
			<son>
				<order>4</order>
				<name>鍋島直英</name>
				<role>肥前小城藩五代藩主</role>
				<birth>1699</birth>
				<death>1744</death>
			</son>
			<daughter>
				<order>1</order>
				<name>式部</name>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<fatherInLaw>
					<role>肥前佐賀藩四代藩主</role>
					<name>鍋島吉茂</name>
				</fatherInLaw>
				<husband>
					<role>三河刈谷藩二代藩主</role>
					<name>三浦明喬</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島元延</name>
	<yomi>motonobu</yomi>
	<birth>1695</birth>
	<death>1714</death>
	<father>
		<role>肥前小城藩三代藩主</role>
		<name>鍋島元武</name>
		<yomi>mototake</yomi>
	</father>
	<altName>
		<first>彦松</first>
		<other>三平</other>
	</altName>
	<profiles>
		<event>
			<start>1709</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1709</start>
			<title>飛騨守</title>
		</event>
		<event>
			<start>1713</start>
			<end>1714</end>
			<title>肥前小城藩四代藩主</title>
		</event>
		<event>
			<start>1714</start>
			<title>加賀守</title>
		</event>
	</profiles>
	<secondWife>
		<name>香田氏</name>
		<children>
				<son>
					<order>1</order>
					<name>鍋島直英</name>
					<yomi>naohide</yomi>
					<role>肥前小城藩五代藩主</role>
					<birth>1699</birth>
					<death>1744</death>
					<adopted>養子</adopted>
				</son>
				<daughter>
					<order>2</order>
					<name>娘</name>
					<husband>
						<name>鍋島茂和</name>
					</husband>
				</daughter>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直英</name>
	<yomi>naohide</yomi>
	<birth>1699</birth>
	<death>1744</death>
	<father>
		<role>肥前小城藩三代藩主</role>
		<name>鍋島元武</name>
		<yomi>mototake</yomi>
	</father>
	<fatherInLaw>
		<role>肥前佐賀藩家老</role>
		<name>多久茂文</name>
	</fatherInLaw>
	<fatherInLaw>
		<role>肥前小城藩四代藩主</role>
		<name>鍋島元延</name>
		<yomi>motonobu</yomi>
	</fatherInLaw>
	<altName>
		<other>出雲</other>
	</altName>
	<profiles>
		<event>
			<start>1711</start>
			<end>1714</end>
			<title>五代多久邑主</title>
		</event>
		<event>
			<start>1714</start>
			<end>1744</end>
			<title>肥前小城藩五代藩主</title>
		</event>
		<event>
			<start>1714</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1714</start>
			<title>加賀守</title>
		</event>
	</profiles>
	<firstWife>
		<name>本良院</name>
		<name>千重子</name>
		<father>
			 <name>多久茂文</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>万之助</name>
			</son>
			<son>
				<order>5</order>
				<name>鍋島直員</name>
				<yomi>naokazu</yomi>
				<role>肥前小城藩六代藩主</role>
				<birth>1726</birth>
				<death>1780</death>
			</son>
			<son>
				<order>7</order>
				<name>鍋島直照</name>
				<fatherInLaw>
					<name>鍋島直祐</name>
				</fatherInLaw>
			</son>
			<son>
				<order>8</order>
				<name>三浦能候</name>
				<fatherInLaw>
					<name>三浦能冬</name>
				</fatherInLaw>
			</son>
			<son>
				<order>9</order>
				<name>田尻維種</name>
				<fatherInLaw>
					<name>田尻松亀某</name>
				</fatherInLaw>
			</son>
 			<daughter>
				<order>2</order>
				<name>娘</name>
				<husband>
					<role>肥前鹿島藩四代藩主</role>
					<name>鍋島直郷</name>
				</husband>
			</daughter>
			<daughter>
					<order>3</order>
					<name>娘</name>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>6</order>
				<name>娘</name>
			</daughter>
			<daughter>
				<order>10</order>
				<name>娘</name>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>中林氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>田島氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>水町公忠</name>
				</husband>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<husband>
					<name>園田忠利</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直員</name>
	<yomi>naokazu</yomi>
	<birth>1726</birth>
	<death>1780</death>
	<father>
		<role>肥前小城藩五代藩主</role>
		<name>鍋島直英</name>
		<yomi>naohide</yomi>
	</father>
	<altName>
		<first>三次郎</first>
	</altName>
	<profiles>
		<event>
			<start>1741</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1741</start>
			<title>紀伊守</title>
		</event>
		<event>
			<start>1744</start>
			<end>1764</end>
			<title>肥前小城藩六代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<name>松子</name>
		<name>静明院</name>
		<fatherInLaw>
			<role>肥前佐賀藩六代藩主</role>
			<name>鍋島宗教</name>
		</fatherInLaw>
		<father>
			<role>権大納言</role>
			<name>五条為範</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直嵩</name>
			</son>
			<son>
				<order>3</order>
				<name>鍋島直愈</name>
				<role>肥前小城藩七代藩主</role>
				<birth>1756</birth>
				<death>1801</death>
			</son>
			<son>
				<order>5</order>
				<name>鍋島直宜</name>
				<birth>1762</birth>
				<death>1820</death>
				<description>肥前鹿島藩へ</description>
			</son>
			<daughter>
				<order>2</order>
				<name>親</name>
				<birth>1755</birth>
				<death>1793</death>
				<fatherInLaw>
					<role>肥前佐賀藩八代藩主</role>
					<name>鍋島治茂</name>
				</fatherInLaw>
				<husband>
					<role>権大納言</role>
					<name>正親町公明</name>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>娘</name>
				<husband>
					<name>鍋島直容</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
	<secondWife>
		<name>某氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<role>十代諫早領主</role>
					<name>諫早茂成</name>
				</husband>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<husband>
					<name>太田増桓</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>松井氏</name>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直賢</name>
				<birth>1758</birth>
				<description>忠茂家系へ</description>
			</son>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<husband>
					<name>鍋島元溥</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>中林氏</name>
		<children>
			<daughter>
				<order>1</order>
				<name>娘</name>
				<husband>
					<name>鍋島能完</name>
				</husband>
			</daughter>
			<daughter>
				<order>2</order>
				<name>娘</name>
				<husband>
					<name>野口能賢</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>原田氏</name>
		<children>
			<son>
				<order>1</order>
				<name>田尻種信</name>
				<fatherInLaw>
					<name>田尻維種</name>
				</fatherInLaw>
			</son>
			<son>
				<order>2</order>
				<name>西頼豊明</name>
				<fatherInLaw>
					<name>西頼豊恭</name>
				</fatherInLaw>
			</son>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直愈</name>
	<yomi>naomasu</yomi>
	<birth>1756</birth>
	<death>1801</death>
	<father>
		<role>肥前小城藩六代藩主</role>
		<name>鍋島直員</name>
		<yomi>naokazu</yomi>
	</father>
	<altName>
		<first>直喬</first>
		<other>伊三郎</other>
	</altName>
	<profiles>
		<event>
			<start>1764</start>
			<end>1794</end>
			<title>肥前小城藩七代藩主</title>
		</event>
		<event>
			<start>1771</start>
			<title>従五位下</title>
		</event>
		<event>
			<start>1771</start>
			<title>加賀守</title>
		</event>
	</profiles>
	<firstWife>
		<name>数子</name>
		<father>
			<role>肥前佐賀藩七代藩主</role>
			<name>鍋島重茂</name>
		</father>
	</firstWife>
	<secondWife>
		<name>タミ</name>
		<name>本性院</name>
		<name>秀島記稔の娘</name>
		<father>
			<name>鍋島重茂</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直知</name>
				<role>肥前小城藩八代藩主</role>
				<birth>1784</birth>
				<death>1804</death>
			</son>
			<son>
				<order>2</order>
				<name>昌右衛門</name>
			</son>
			<daughter>
				<order>3</order>
				<name>篤子</name>
				<death>1877</death>
				<husband>
					<role>肥前鹿島藩七代藩主</role>
					<name>鍋島直彜</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
	<secondWife>
		<name>三笠</name>
		<name>良峰院</name>
		<name>松崎利如の娘</name>
		<children>
			<son>
				<order>1</order>
				<name>万丸</name>
			</son>
			<son>
				<order>2</order>
				<name>鶴丸</name>
			</son>
			<son>
				<order>3</order>
				<name>鍋島直堯</name>
				<role>肥前小城藩九代藩主</role>
				<birth>1800</birth>
				<death>1873</death>
			</son>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直知</name>
	<yomi>naotomo</yomi>
	<birth>1784</birth>
	<death>1804</death>
	<father>
		<role>肥前小城藩七代藩主</role>
		<name>鍋島直愈</name>
		<yomi>naomasu</yomi>
	</father>
	<altName>
		<first>麟太郎</first>
		<other>紀伊守</other>
	</altName>
	<profiles>
		<event>
			<start>1794</start>
			<end>1804</end>
			<title>肥前小城藩八代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直堯</name>
				<role>肥前小城藩九代藩主</role>
				<birth>1800</birth>
				<death>1873</death>
				<adopted>養子</adopted>
			</son>
		</children>
	</firstWife>
</hansyu>

<hansyu>
	<name>鍋島直堯</name>
	<yomi>naotaka</yomi>
	<birth>1800</birth>
	<death>1873</death>
	<father>
		<role>肥前小城藩七代藩主</role>
		<name>鍋島直愈</name>
		<yomi>naomasu</yomi>
	</father>
	<fatherInLaw>
		<role>肥前小城藩八代藩主</role>
		<name>鍋島直知</name>
		<yomi>naotomo</yomi>
	</fatherInLaw>
	<altName>
		<first>捨丸</first>
		<other>直基</other>
		<other>加賀守</other>
		<other>紀伊守</other>
	</altName>
	<profiles>
		<event>
			<start>1804</start>
			<end>1850</end>
			<title>肥前小城藩九代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<name>多久橘</name>
		<father>
			<name>多久茂鄰</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直亮</name>
				<role>肥前小城藩十代藩主</role>
				<birth>1829</birth>
				<death>1864</death>
			</son>
			<daughter>
				<order>2</order>
				<name>常子</name>
				<birth>1837</birth>
				<death>1862</death>
				<husband>
					<role>肥前蓮池藩九代藩主</role>
					<name>鍋島直紀</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
</hansyu>

<hansyu>
	<name>鍋島直亮</name>
	<yomi>naosuke</yomi>
	<birth>1829</birth>
	<death>1864</death>
	<father>
		<role>肥前小城藩九代藩主</role>
		<name>鍋島直堯</name>
		<yomi>naotaka</yomi>
	</father>
	<altName>
		<first>三平</first>
		<other>加賀守</other>
	</altName>
	<profiles>
		<event>
			<start>1850</start>
			<end>1864</end>
			<title>肥前小城藩十代藩主</title>
		</event>
	</profiles>
	<firstWife>
		<name>鍋島結</name>
		<fatherInLaw>
			<role>肥前佐賀藩十代藩主</role>
			<name>鍋島直正</name>
			<altName>
				<first>閑叟</first>
			</altName>
		</fatherInLaw>
		<father>
			<role>肥前鹿島藩八代藩主</role>
			<name>鍋島直永</name>
		</father>
		<children>
			<son>
				<order>2</order>
				<name>鍋島直虎</name>
				<role>肥前小城藩十一代藩主</role>
				<birth>1856</birth>
				<death>1925</death>
				<adopted>養子</adopted>
			</son>
			<daughter>
				<order>1</order>
				<name>鍋島春子</name>
				<birth>1851</birth>
				<death>1894</death>
				<husband>
					<role>子爵</role>
					<name>鍋島直虎</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
</hansyu>

<hansyu>
	<name>鍋島直虎</name>
	<yomi>naotora</yomi>
	<birth>1856</birth>
	<death>1925</death>
	<father>
		<role>肥前佐賀藩十代藩主</role>
		<name>鍋島直正</name>
		<altName>
			<first>閑叟</first>
		</altName>
	</father>
	<fatherInLaw>
		<role>肥前小城藩十代藩主</role>
		<name>鍋島直亮</name>
		<yomi>naosuke</yomi>
	</fatherInLaw>
	<altName>
		<first>欽八郎</first>
		<other>紀伊守</other>
	</altName>
	<profiles>
		<event>
			<start>1864</start>
			<end>1869</end>
			<title>肥前小城藩十一代藩主</title>
		</event>
		<event>
			<start>1869</start>
			<end>1871</end>
			<title>小城藩知事</title>
		</event>
		<event>
			<title>外務省御用掛</title>
		</event>
		<event>
			<start>1884</start>
			<end>1925</end>
			<title>子爵</title>
		</event>
		<event>
			<start>1890</start>
			<title>貴族院議員</title>
		</event>
	</profiles>
	<firstWife>
		<name>鍋島春子</name>
		<father>
			<role>肥前小城藩十代藩主</role>
			<name>鍋島直亮</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直庸</name>
				<role>肥前小城藩十四代藩主</role>
				<birth>1879</birth>
				<death>1962</death>
			</son>
		</children>
	</firstWife>
	<secondWife>
		<name>南部貴子</name>
		<father>
			<role>陸奥盛岡藩十四代藩主</role>
			<name>南部利剛</name>
		</father>
		<children>
			<son>
				<order>3</order>
				<name>鍋島直顕</name>
				<role>肥前小城藩十二代藩主</role>
				<birth>1901</birth>
				<death>1989</death>
			</son>
			<daughter>
				<order>1</order>
				<name>内山好子</name>
				<birth>1896</birth>
			</daughter>
			<daughter>
				<order>2</order>
				<name>慶子</name>
				<birth>1899</birth>
				<death>1978</death>
				<husband>
					<role>子爵</role>
					<name>本多忠昭</name>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>鏉子</name>
				<birth>1902</birth>
				<death>1980</death>
				<husband>
					<role>男爵</role>
					<name>毛利元良</name>
				</husband>
			</daughter>
		</children>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直顕</name>
	<yomi>naoaki</yomi>
	<role>バイオリニスト</role>
	<birth>1901</birth>
	<death>1989</death>
	<father>
		<role>肥前小城藩十一代藩主</role>
		<role>子爵</role>
		<name>鍋島直虎</name>
		<yomi>naotora</yomi>
	</father>
	<profiles>
		<event>
			<start>1901</start>
			<title>分家</title>
		</event>
	</profiles>
	<firstWife>
		<name>高木治代</name>
		<birth>1907</birth>
		<death>1981</death>
		<father>
			<name>高木正秋</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直昶</name>
				<yomi>naoteru</yomi>
				<role>肥前小城藩十三代藩主</role>
				<birth>1926</birth>
			</son>
		</children>
	</firstWife>
</hansyu>

<hansyu>
	<name>鍋島直昶</name>
	<yomi>naoteru</yomi>
	<role>海軍航空隊員</role>
	<role>関西佐賀県人会理事</role>
	<role>小城会会長</role>
	<birth>1926</birth>
	<father>
		<role>肥前小城藩十二代藩主</role>
		<name>鍋島直顕</name>
		<yomi>naoaki</yomi>
	</father>
	<profiles>
		<event>
			<start>2008</start>
			<title>ゴールデン・シニア・トリオ結成</title>
		</event>
		<event>
			<start>2015</start>
			<title>世界最高齢バンド</title>
		</event>
		<event>
			<start>2015</start>
			<title>『1億人の大質問!?笑ってコラえて!』出演</title>
		</event>
	</profiles>
</hansyu>

<hansyu>
	<name>鍋島直庸</name>
	<yomi>naoyou</yomi>
	<role>主猟官</role>
	<birth>1879</birth>
	<death>1962</death>
	<father>
		<role>肥前小城藩十一代藩主</role>
		<role>子爵</role>
		<name>鍋島直虎</name>
		<yomi>naotora</yomi>
	</father>
	<profiles>
		<event>
			<start>1925</start>
			<end>1947</end>
			<title>子爵</title>
		</event>
	</profiles>
	<firstWife>
		<name>松平清子</name>
		<father>
			<role>伯爵</role>
			<name>松平茂昭</name>
			<altName>
				<first>直廉</first>
			</altName>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直浩</name>
				<role>肥前小城藩十五代藩主</role>
				<birth>1906</birth>
				<death>1968</death>
			</son>
			<son>
				<order>2</order>
				<name>三宅直胖</name>
				<birth>1907</birth>
				<death>1939</death>
				<description>三宅氏へ</description>
			</son>
			<daughter>
				<order>3</order>
				<name>京子</name>
				<birth>1913</birth>
				<husband>
					<name>千葉常五郎</name>
				</husband>
			</daughter>
			<daughter>
				<order>4</order>
				<name>福子</name>
				<birth>1914</birth>
				<husband>
					<role>伯爵</role>
					<name>山田顕貞</name>
				</husband>
			</daughter>
		</children>
	</firstWife>
</hansyu>

<hansyu>
	<name>鍋島直浩</name>
	<yomi>naoharu</yomi>
	<role>陸軍砲兵中尉</role>
	<birth>1906</birth>
	<death>1968</death>
	<father>
		<role>肥前小城藩十四代藩主</role>
		<role>子爵</role>
		<name>鍋島直庸</name>
		<yomi>naoyou</yomi>
	</father>
	<firstWife>
		<name>一条重子</name>
		<father>
			<role>公爵</role>
			<name>一条実孝</name>
		</father>
		<children>
			<son>
				<order>1</order>
				<name>鍋島直幸</name>
				<role>肥前小城藩十六代藩主</role>
				<birth>1931</birth>
			</son>
			<son>
				<order>2</order>
				<name>直佑</name>
				<birth>1933</birth>
				<wife>
					<name>弘子</name>
					<birth>1940</birth>
					<mother><name>奥村花江</name></mother>
				</wife>
			</son>
			<son>
				<order>3</order>
				<name>直良</name>
				<birth>1935</birth>
				<wife>
					<name>嘉子</name>
					<birth>1935</birth>
					<mother><name>杉本幸子</name></mother>
				</wife>
			</son>
			<son>
				<order>4</order>
				<name>直克</name>
				<birth>1941</birth>
				<death>1986</death>
				<wife>
					<name>翠</name>
					<birth>1941</birth>
					<mother><name>元崎信</name></mother>
				</wife>
			</son>
		</children>
	</firstWife>
	<secondWife>
		<name>城和子</name>
		<birth>1919</birth>
		<father>
			<name>城幸助</name>
		</father>
	</secondWife>
</hansyu>

<hansyu>
	<name>鍋島直幸</name>
	<yomi>naoyuki</yomi>
	<birth>1931</birth>
	<father>
		<role>肥前小城藩十五代藩主</role>
		<name>鍋島直浩</name>
		<yomi>naoharu</yomi>
	</father>
	<firstWife>
		<name>中川房江</name>
		<birth>1936</birth>
		<father>
			<name>中川田州</name>
		</father>
		<children>
			<daughter>
				<order>1</order>
				<name>元子</name>
				<birth>1960</birth>
			</daughter>
			<daughter>
				<order>2</order>
				<name>理恵子</name>
				<birth>1965</birth>
			</daughter>
		</children>
	</firstWife>
</hansyu>
</ogiNabeshima>